#!/usr/local/bin/lua

require "luarocks.loader"
require "ursa"

-- Filename list for Glop core
local glop_filenames = {"Base", "Input", "GlopFrameBase", "GlopFrameStyle", "GlopWindow", "System", "Utils", "GlopInternalData", "OpenGl", "Collisions", "Font", "GlopFrameWidgets", "Image", "Thread", "Sound", "Stream", "glop3d/Camera", "glop3d/Mesh", "glop3d/Point3"}

-- basic initial setup and configuration
local flags = {}
do
  ursa.token.rule{"os_name", nil, "uname -o"}
  local local_os = ursa.token{"os_name"}

  if local_os == "Cygwin" then
    local_os = "cygwin"
    
    flags.cxx = "-mno-cygwin -DWIN32 -D_LIB -D_MBCS -I/usr/local/include -O2"
    flags.ld = "-mno-cygwin -LGlop/cygwin/lib -L/lib/mingw -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -luuid -lodbc32 -lodbccp32 -lopengl32 -lfreetype -ljpeg -lglu32 -ldinput -ldxguid -lfmodex -lwinmm -lpng -O2"
    
    table.insert(glop_filenames, "OsWin32")
  else
    assert(false)
  end
  
  flags.cxx = flags.cxx .. " -IGlop/cygwin/include -IGlop/source -I. -O2 -g"
end

-- parse the result from g++'s built-in dependency scanner
local function make_dependencies(srcfile)
  local deps = ursa.util.system{("g++ %s -MM %s"):format(flags.cxx, srcfile)}
  deps = deps:match("^.*: (.*)$")
  
  local dependencies = {}
  for file in deps:gmatch("([^ \n\t]+)") do
    if file ~= "\\" then
      table.insert(dependencies, file)
    end
  end
  
  return dependencies
end

-- build the source files
local objects = {}
for _, file in ipairs(glop_filenames) do
  local cpp = "Glop/source/" .. file .. ".cpp"
  local o = "build/Glop/" .. file .. ".o"
  local depend = "Glop/" .. file .. " dependencies"
  
  ursa.token.rule{depend, ursa.util.token_deferred{depend, default = cpp}, function () return make_dependencies(cpp) end}
  table.insert(objects, ursa.rule{o, ursa.util.token_deferred{depend}, ("g++ %s -o %s -c %s"):format(flags.cxx, o, cpp)})
end

local fullglop = {}

-- build the glop library
table.insert(fullglop, ursa.rule{"build/Glop/lib/libGlop.a", objects, ursa.util.system_template{"ar rc $TARGET $SOURCES"}})

-- mirror source files into the appropriate build directory
ursa.token.rule{"headers", nil, "cd Glop/source && find -type f | sed s*\\\\./**"}
for k in ursa.token{"headers"}:gmatch("[^%s]+") do
  table.insert(fullglop, ursa.rule{"build/Glop/include/Glop/" .. k, "Glop/source/" .. k, ursa.util.system_template{"cp $SOURCE $TARGET"}})
end

ursa.command{"glop", fullglop}



-- let's have some actual apps
local applist = {}
local function BuildApp(appname, files)
  local objects = {}
  for _, file in ipairs(files) do
    local cpp = ("%s/%s.cpp"):format(appname, file)
    local o = ("build/%s/%s.o"):format(appname, file)
    local depend = ("%s/%s dependencies"):format(appname, file)
    
    ursa.token.rule{depend, ursa.util.token_deferred{depend, default = cpp}, function () return make_dependencies(cpp) end}
    table.insert(objects, ursa.rule{o, ursa.util.token_deferred{depend}, ("g++ %s -o %s -c %s"):format(flags.cxx, o, cpp)})
  end
  
  local out = "build/" .. appname .. ".exe"
  table.insert(applist, ursa.rule{out, {objects, "build/libGlop.a"}, ursa.util.system_template{("g++ -o $TARGET $SOURCES %s"):format(flags.ld)}})
end

BuildApp("Tests", {"Tests"})

ursa.command{ursa.command.default, applist}

-- clean things up properly

if not clean_dirs then clean_dirs = {} end
table.insert(clean_dirs, "build/Glop/glop3d")
table.insert(clean_dirs, "build/Glop")
table.insert(clean_dirs, "build/Tests")
table.insert(clean_dirs, "build")

ursa.command{"clean", function ()
  ursa.util.clean()
  for _, v in ipairs(clean_dirs) do
    os.remove(v)
  end
end}

ursa.build{...}


return {lib = fullglop[1], package = fullglop} -- just in case we're being shelled by something, here's the glop package data
