Import('env')
Export('env')
Glop = env['Glop']

env.Application(
    target = 'Test',
    source = 'Tests.cpp',
    frameworks = Glop,
    resources = [
        'Icon.bmp',
        'ninja.jpg',
        'thames.ttf',
        'glop.jpg',
    ]
)
