import os
Import('env')
Export('env')

env.Replace(PROJECT_ROOT = os.path.join(env['PROJECT_ROOT'], 'source' + os.sep))
env.Replace(BUILD_ROOT   = os.path.join(env['BUILD_ROOT']  , 'source' + os.sep))
env.Append(CPPPATH = ['#Glop/source/'])

package = env.LoadPackage('/glop')
Glop = env.CompleteLibrary(
    objs = package['objects'],
    headers = package['headers'],
    libs = package['libs'],
    framework_structure = env['GLOBAL_ROOT'] + 'Glop/OSX/framework.framework')
Return('Glop')
