import SCons.Util
import scons_utils
Import('env')
Export('env')

env.BuildObjects(
  target_name = 'base',
  source = [
    'Point2.cpp',
  ],
  headers = [
    'Point2.h',
  ]
)

env.Test('test', 'Point2_test.cpp', packages = ['base'])
