import SCons.Util
import scons_utils
Import('env')
Export('env')

env.BuildObjects(
  target_name = 'base',
  source = [
    'NetworkManager.cpp',
  ],
  headers = [
    'NetworkManagerInterface.h',
    'NetworkManager.h',
  ],
  libs = [
    'rakneti386',
  ],
)

env.BuildObjects(
  target_name = 'mock',
  source = [
    'MockNetworkManager.cpp',
    'MockRouter.cpp',
  ],
  headers = [
  ],
  packages = [
  ],
)

env.Test(
  'network_manager_test',
  'NetworkManager_test.cpp',
  packages = ['base', '/glop']
)
env.Test(
  'mock_network_manager_test',
  'MockNetworkManager_test.cpp',
  packages = ['mock', '/glop']
)
